### ISSUE TITLE
Password compounding with old username entry

### ISSUE THREAD

**Issue by jaroszke** [onlykey/OnlyKey-Firmware-US#12]
password output compounded with old username, 
I set a username in each slot, then reset username with a password. The output of the new username works but the password compounds the old username to it.

https://lh6.googleusercontent.com/rb-EQzrUidrkI3PcUc1V0zpCHq1HGhfhAAzTh0-Hclie5yPyx7w0sWJkK1o1GcVRzrpAKgFKth1c7VD5OSbNwFSz2kvfTZHrBUUKBpfpBNMddLg855Njb1YxO905O6Yi63Y

**Comment by onlykey** [comment]
fixed
