### ISSUE TITLE
Pass output error (High)

### ISSUE THREAD

**Issue by jaroszke** [onlykey/OnlyKey-Firmware-US#14]
Setting Slot, only set password field to "pass", output includes additional number "pass6508"

Serial Monitor
![image](https://cloud.githubusercontent.com/assets/9595840/16028564/87b02eae-31ae-11e6-8141-266ecf56e46d.png)

Chrome App Log
![image](https://cloud.githubusercontent.com/assets/9595840/16028604/d586c778-31ae-11e6-8db7-d66c4c0eac2c.png)

**Comment by onlykey** [comment]
Fixed, wipe keybuffer from RAM
