### ISSUE TITLE
Slot 5 not outputting

### ISSUE THREAD

**Issue by onlykeytesting** [onlykey/OnlyKey-Firmware-US#3]
Configured slot 5a with Username and Pass, when pressed doesn't output, serial monitor output below

Slot Number 6

Displaying Full Keybuffer

esttest1

**Comment by onlykey** [comment]
I tried to replicate this. For slot 5a I did see there is a delay in the label appearing on the app but the information you enter is typed out correctly.

**Comment by rodgolpe** [comment]
I cannot replicate this issue either.

**Comment by onlykeytesting** [comment]
Have to keep this onlykeytesting person anonymous lol, I guess this is what happens when you log in to the testing account and then forget to logout :)

**Comment by onlykey** [comment]
Sounds like your OK has a bad button #5
