### ISSUE TITLE
Slot 1a label missing pipe separator.

### ISSUE THREAD

**Issue by rodgolpe** [onlykey/OnlyKey-Firmware-US#4]
After calling OKGETLABELS, slot 1a is consistently returned without the required pipe separator (|). This causes issues when displaying labels in the Chrome app. If slot 1a's label is not set, all other labels are "shifted" up by 1 slot.

**Comment by onlykey** [comment]
Issue has been addressed and also serial.print of labels now so if there is any issue check serial monitor.
