### ISSUE TITLE
OKWIPESLOT does not wipe slot.

### ISSUE THREAD

**Issue by rodgolpe** [onlykey/OnlyKey-Firmware-US#5]
When the Chrome app sends OKWIPESLOT, slot data still seems to be set. Pressing a "wiped" slot button continues to output usernames and passwords.

Serial Monitor shows:
Received packetFFFFFFFFE710000000000000000000000000000000000000000000000000000000000OKWIPESLOT MESSAGE RECEIVED:67
Wiping Slot #1
Value #0
000000000000000000000000000000000000000000000000000000000Overwriting slot with 0s

**Comment by onlykey** [comment]
It was looking for value 0 which does not exist. Since wipe slot wipes the whole slot and not just certain fields it was an easy fix.
